sudo: false
language: php

php:
  - 7.4

before_script:
  - travis_retry composer install --no-interaction --prefer-dist --no-progress --no-suggest
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

branches:
  only:
    - master

#cache:
#  directories:
#    - vendor

script:
  - 'if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then vendor/bin/phpunit; fi'
  #- 'if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then php arty soracom:latest; fi'

after_script:
  - ./cc-test-reporter after-build -t clover --exit-code $TRAVIS_TEST_RESULT
