name: tests
on:
  schedule:
  - cron: 5 3 * * *

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    env:
        DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
        DISCORD_CHANNEL: ${{ secrets.DISCORD_CHANNEL }}
        SORACOM_ID: ${{ secrets.SORACOM_ID }}
        SORACOM_SECRET: ${{ secrets.SORACOM_SECRET }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: '7.4'
          extensions: mbstring, bcmath
          coverage: xdebug #optional
      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.7.4
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: vendor/bin/phpunit
          coverageLocations: build/logs/clover.xml:clover
